#!/bin/bash
# When run in sandbox, external repositories are in the execroot
WASI_SDK_DIR="external/+_repo_rules+wasi_sdk"
if [ ! -d "$WASI_SDK_DIR" ]; then
    WASI_SDK_DIR="external/wasi_sdk"
fi
exec "$WASI_SDK_DIR/bin/clang" "$@"
